### ISSUE TITLE
How to build our own server with private data if we don't use docker?

### ISSUE THREAD

**Issue by xuzhang5788** [n-yoshikawa/molecule-sanitizer#1]
Thank you so much for your great repo and website. If I don't use docker, how do I build our own server? Many thanks

**Comment by n-yoshikawa** [comment]
Thank you for your inquiry. You just need to install dependencies in your envrionment to build your own server.

All dependencies can be installed via pip. 

```
pip install Django social-auth-app-django rdkit-pypi pandas annoy
```

After that, clone this repo and follow the step 3 in README. 

You need to set up API keys and callback URL properly.
If you have any problems in installation, please feel free to ask more questions.
